packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: 5.0.1
  '@vitest/coverage-v8': 5.0.1

overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
    - vite-plus
    - esbuild
  allowedVersions:
    vite: '*'
    vitest: '*'
